import { Inter } from 'next/font/google'
import Head from 'next/head'
import Image from 'next/image'
import cx from "classnames";
import Card from '@/components/Card';
import Button from '@/components/Button';
import Text from '@/components/Text';

const inter = Inter({ subsets: ['latin'] })

type CardLabel = {
  status: string
}
interface CardItem extends CardLabel {
  clientLogo: string
  approval: string
  client: string
  date: string
  img: string
  owner: string
}


const CardLabel = ({ status }: CardLabel) => {
  return <>
    {
      {
        "In progress": <div className="w-[100px] h-5 bg-[#FCE513] flex items-center justify-center rounded-[5px] text-black"><Text type="sub">{status}</Text></div>,
        "1st revision": <div className="w-[100px] h-5 bg-[#F4B000] flex items-center justify-center rounded-[5px] text-black"><Text type="sub">{status}</Text></div>,
        "2nd revision": <div className="w-[100px] h-5 bg-[#F47500] flex items-center justify-center rounded-[5px] text-black"><Text type="sub">{status}</Text></div>,
        default: <div className="w-[100px] h-5 bg-black text-white flex items-center justify-center rounded-[5px]"><Text type="sub">{status}</Text></div>
      }[status]
    }
  </>
}

const stringToColour = (str: string): string => {
  var hash = 0;
  for (var i = 0; i < str.length; i++) {
    hash = str.charCodeAt(i) + ((hash << 5) - hash);
  }
  var colour = '#';
  for (var i = 0; i < 3; i++) {
    var value = (hash >> (i * 8)) & 0xFF;
    colour += ('00' + value.toString(16)).substr(-2);
  }
  return colour;
}

interface AvatarLetter {
  name: string
  color: string
}

const AvatarLetter = ({ name, color }: AvatarLetter) => {
  return <div className="h-[22px] w-[22px] rounded-full flex justify-center items-center" style={{ backgroundColor: color }}>{name.charAt(0).toUpperCase()}</div>
}

const CardItem = ({
  clientLogo,
  approval,
  client,
  img,
  owner,
  status,
  date }: CardItem) => {
  return <div className="w-full flex py-[14px] px-4 h-[70px] border border-black rounded-[5px]">
    <div className="text-black min-w-[72px]">
      <Image
        src={clientLogo}
        alt="client-logo"
        width={44}
        height={44}
      />
    </div>
    <div className="w-full whitespace-nowrap overflow-hidden text-ellipsis mr-8 flex items-center">
      <Text type="main">{approval}</Text>
    </div>
    <div className="text-black min-w-[180px] gap-2 flex items-center">
      <AvatarLetter name={client} color={stringToColour(client)} />
      <Text type="sub">{client}</Text>
    </div>
    <div className="flex gap-[8.33px] text-black min-w-[162px] items-center">
      <div className="w-[22px] h-[22px] rounded-full">
        <Image
          src={img}
          alt="thumnail"
          width={22}
          height={22}
        />
      </div>
      <Text type="sub">{owner}</Text>
    </div>
    <div className="text-black min-w-[164px] flex items-center"><Text type="sub">{date}</Text></div>
    <div className="min-w-[150px] flex items-center">
      <CardLabel status={status} />
    </div>
  </div>
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Gemstar Assesment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex h-[65px]">
        <aside className="min-w-[295px] w-[295px] bg-[#1E67AF] p-[8px_77px_6px_83px]">
          <p className="text-[40px] leading-[48.41px] h-[51px]">LOGO</p>
        </aside>
        <section className="flex w-full bg-white drop-shadow-[2px_2px_4px_rgba(0,0,0,0.05)]">
          <div className="h-full w-full">
            <input
              className="h-full w-full bg-[33px] outline-none px-[60px] bg-transparent text-black bg-[url('/search-icon.svg')] bg-no-repeat bg-scroll"
              placeholder="Search anything here..."
            />
          </div>
          <div className="flex justify-end items-center min-w-fit mr-[25px] gap-[25px]">
            <div className="flex items-center gap-[11px] flex-row w-fit">
              <Image
                src="/out-logo.svg"
                alt="logout"
                width={25}
                height={20}
                priority
              />
              <Text type="main" className="text-[#EE0D0D]">Logout</Text>
            </div>
            <Image
              src="/hamburger-menu.svg"
              alt="hamburger-menu"
              width={25}
              height={20}
              priority
            />
          </div>
        </section>
      </header>
      <main className="flex flex-row">
        <aside className="pt-[56px] bg-white min-w-[295px] w-[295px] px-7 min-h-[calc(100vh_-_65px)] drop-shadow-[2px_2px_4px_rgba(0,0,0,0.05)]">
          <section className="border-b border-[#DCDCDC] w-full pb-[29px]">
            <div className="h-[63px] w-[63px] rounded-full bg-[#D9D9D9] mb-[17px]"></div>
            <Text type="main">Radhika Dhawan Puri</Text>
            <Text type="sub">Senior Client Services</Text>
          </section>
          <section className="border-b border-[#DCDCDC] w-full pt-[29px] pb-[46px]">
            <Text type="small" className="mb-3 uppercase">Navigation</Text>
            <div className="flex flex-col gap-[10px]">
              <div className="flex gap-3">
                <Image
                  src="/dashboard.svg"
                  alt="dashboard"
                  width={15}
                  height={15}
                  priority
                />
                <Text type="main" className="hover:text-[#1E67AF] cursor-pointer">Dashboard</Text>
              </div>
              <div className="flex gap-3">
                <Image
                  src="/approval.svg"
                  alt="approval"
                  width={14.4}
                  height={16}
                  priority
                />
                <Text type="main" className="hover:text-[#1E67AF] cursor-pointer">Approvals</Text>
              </div>
            </div>
          </section>
          <section className="w-full pt-[29px]">
            <Text type="small" className="mb-3 uppercase">My Account</Text>
            <div className="flex flex-col gap-[10px]">
              <div className="flex gap-3">
                <Image
                  src="/client.svg"
                  alt="client"
                  width={16.5}
                  height={18.33}
                  priority
                />
                <Text type="main" className="hover:text-[#1E67AF] cursor-pointer">My Clients</Text>
              </div>
              <div className="flex gap-3">
                <Image
                  src="/cog.svg"
                  alt="profile"
                  width={15.61}
                  height={15}
                  priority
                />
                <Text type="main" className="hover:text-[#1E67AF] cursor-pointer">Edit profiles</Text></div>
            </div>
          </section>
        </aside>
        <section className="p-[33px] w-[calc(100vw_-_292px)] h-full min-h-[calc(100vh_-_65px)]">
          <header className="mb-11">
            <Text type="h1">Hi Radhika, welcome back!</Text>
          </header>
          <article className="mb-14">
            <header className="mb-6">
              <Text type="h4">Your client list</Text>
              <Text type="sub">You currently servicing 3 clients</Text>
            </header>
            <section className="flex gap-[15px] flex-wrap">
              <Card className="w-[259px] h-[184px] p-[21px]">
                <header className="flex justify-between h-[31px] mb-[9px]">
                  <Image
                    src="/dbs-logo.svg"
                    alt="company-logo"
                    width={99}
                    height={28.87}
                  />
                  <Image
                    src="/elipsis.svg"
                    alt="menu"
                    width={21}
                    height={21}
                    className="self-start relative top-[-15px] right-[-11px]"
                  />
                </header>
                <article>
                  <Text type="main" className="mb-[6px]">DBS Bank</Text>
                  <Text type="small">DBS Bank Limited is a Singaporean multinational banking and financial services corporation headquartered at the Marina Bay Financial Centre in the Marina Bay district of Singapore.</Text>
                </article>
              </Card>
              <Card className="w-[259px] h-[184px] p-[21px]">
                <header className="flex justify-between h-[31px] mb-[9px] relative">
                  <Image
                    src="/proudfoot-logo.svg"
                    alt="company-logo"
                    width={70}
                    height={47}
                    className="min-h-[47px] relative top-[-10px]"
                  />
                  <Image
                    src="/elipsis.svg"
                    alt="menu"
                    width={21}
                    height={21}
                    className="self-start relative top-[-15px] right-[-11px]"
                  />
                </header>
                <article>
                  <Text type="main" className="mb-[6px]">Proudfoot</Text>
                  <Text type="small">Proudfoot engages teams and leadership, at all levels, to create innovative solutions to operational constraints and solve the people challenge associated with making sure that change takes place.</Text>
                </article>
              </Card>
              <Card className="w-[259px] h-[184px] p-[21px]">
                <header className="flex justify-between h-[31px] mb-[9px]">
                  <Image
                    src="/rmi-logo.svg"
                    alt="company-logo"
                    width={169}
                    height={26}
                  />
                  <Image
                    src="/elipsis.svg"
                    alt="menu"
                    width={21}
                    height={21}
                    className="self-start relative top-[-15px] right-[-11px]"
                  />
                </header>
                <article>
                  <Text type="main" className="mb-[6px]">RMI</Text>
                  <Text type="small">RMI is a trusted global verification partner for Asia-Pacific organisations, offering a highly personalised and comprehensive background screening service.</Text>
                </article>
              </Card>
            </section>
          </article>
          <article>
            <header className="mb-6 flex justify-between items-center">
              <div>
                <Text type="h4">Recent approvals</Text>
                <Text type="sub">You can find the recent on-going approvals here</Text>
              </div>
              <Button
                icon="/plus.svg"
                iconSize="14px"
                iconColor="white"
                text="Create new approval"
                color="#1E67AF"
                textColor="white"
              />
            </header>
            <section>
              <Card className="flex py-[14px] px-4 border border-black mb-[13px] ">
                <div className="text-black text-sm min-w-[72px]">
                  <Text type="sub">Clients</Text>
                </div>
                <div className="text-black text-sm  w-full">
                  <Text type="sub">Approval Name</Text>
                </div>
                <div className="text-black text-sm min-w-[180px]">
                  <Text type="sub">Client contact</Text>
                </div>
                <div className="text-black text-sm min-w-[162px]">
                  <Text type="sub">Owner</Text>
                </div>
                <div className="text-black text-sm min-w-[164px]">Date Issued</div>
                <div className="text-black text-sm min-w-[150px]">
                  <Text type="sub">Status</Text>
                </div>
              </Card>
              <main className="flex flex-col gap-[13px] mb-[15px]">
                <CardItem
                  clientLogo="/dbs-client.svg"
                  approval="DBS DEG renewal energy LinkedIn post tiles... "
                  client="Jasmine"
                  img="/image.png"
                  owner="Radhika"
                  date="January 23, 2022"
                  status="In progress" />
                <CardItem
                  clientLogo="/proudfoot-client.svg"
                  approval="PF website mining and metals edit"
                  client="Lorena"
                  img="/image.png"
                  owner="Radhika"
                  date="January 23, 2022"
                  status="1st revision" />
                <CardItem
                  clientLogo="/rmi-client.svg"
                  approval="RMI January newletter EDM"
                  client="Mervyn"
                  img="/image.png"
                  owner="Radhika"
                  date="January 23, 2022"
                  status="2nd revision"
                />
              </main>
              <footer>
                <Text type="main" className="text-[#1E67AF]">See all approvals here</Text>
              </footer>
            </section>
          </article>
          <footer className="absolute bottom-[25px] right-9">
            <Text type="sub" className="relative">© Manning&Co. 2022</Text>
          </footer>
        </section>
      </main >
    </>
  )
}
